services:
  couchdb-clone:
    build:
      context: ..
      dockerfile: prod/Dockerfile
    ports:
      - "5984:5984"
    volumes:
      - couchdb-clone-data:/data
    restart: unless-stopped

volumes:
  couchdb-clone-data:
