services:
  nyxdb:
    build:
      context: ..
      dockerfile: prod/Dockerfile
    ports:
      - "5984:5984"
    volumes:
      - nyxdb-data:/data
    restart: unless-stopped

volumes:
  nyxdb-data:
